# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-moe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ios-moe
  pod 'Firebase/Core', '5.2.0'      # !! and here !!
  pod 'Firebase/Storage', '5.2.0'
  pod 'Firebase/Database', '5.2.0'
  pod 'Firebase/Crash', '5.2.0'
  pod 'Firebase/Auth', '5.2.0'
  pod 'Firebase/Messaging', '5.2.0'
  pod 'GoogleSignIn', '4.1.2'

end

target 'ios-moe-Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ios-moe-Test

end
