target 'ios-moe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ios-moe
  pod 'Firebase/Core', '5.2.0'
  pod 'Firebase/Storage', '5.2.0'
  pod 'Firebase/Database', '5.2.0'
  pod 'Firebase/Auth', '5.2.0'
  pod 'Firebase/Messaging', '5.2.0'
  pod 'GoogleSignIn', '4.1.2'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'
  
end
# !! add this also !!
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end